In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [2]:
data = pd.read_csv("HousePricePrediction (2).csv")
data.head()

,Id,MSSubClass,MSZoning,LotArea,LotConfig,BldgType,OverallCond,YearBuilt,YearRemodAdd,Exterior1st,BsmtFinSF2,TotalBsmtSF,SalePrice
0,0,60,RL,8450,Inside,1Fam,5,2003,2003,VinylSd,0.0,856.0,208500.0
1,1,20,RL,9600,FR2,1Fam,8,1976,1976,MetalSd,0.0,1262.0,181500.0
2,2,60,RL,11250,Inside,1Fam,5,2001,2002,VinylSd,0.0,920.0,223500.0
3,3,70,RL,9550,Corner,1Fam,5,1915,1970,Wd Sdng,0.0,756.0,140000.0
4,4,60,RL,14260,FR2,1Fam,5,2000,2000,VinylSd,0.0,1145.0,250000.0

In [3]:
data.shape

(2919, 13)

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2919 entries, 0 to 2918
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Id            2919 non-null   int64
 1   MSSubClass    2919 non-null   int64
 2   MSZoning      2915 non-null   object
 3   LotArea       2919 non-null   int64
 4   LotConfig     2919 non-null   object
 5   BldgType      2919 non-null   object
 6   OverallCond   2919 non-null   int64
 7   YearBuilt     2919 non-null   int64
 8   YearRemodAdd  2919 non-null   int64
 9   Exterior1st   2918 non-null   object
 10  BsmtFinSF2    2918 non-null   float64
 11  TotalBsmtSF   2918 non-null   float64
 12  SalePrice     1460 non-null   float64
dtypes: float64(3), int64(6), object(4)
memory usage: 296.6+ KB

In [5]:
data.describe()

,Id,MSSubClass,LotArea,OverallCond,YearBuilt,YearRemodAdd,BsmtFinSF2,TotalBsmtSF,SalePrice
count,2919.000000,2919.000000,2919.000000,2919.000000,2919.000000,2919.000000,2918.000000,2918.000000,1460.000000
mean,1459.000000,57.137718,10168.114080,5.564577,1971.312778,1984.264474,49.582248,1051.777587,180921.195890
std,842.787043,42.517628,7886.996359,1.113131,30.291442,20.894344,169.205611,440.766258,79442.502883
min,0.000000,20.000000,1300.000000,1.000000,1872.000000,1950.000000,0.000000,0.000000,34900.000000
25%,729.500000,20.000000,7478.000000,5.000000,1953.500000,1965.000000,0.000000,793.000000,129975.000000
50%,1459.000000,50.000000,9453.000000,5.000000,1973.000000,1993.000000,0.000000,989.500000,163000.000000
75%,2188.500000,70.000000,11570.000000,6.000000,2001.000000,2004.000000,0.000000,1302.000000,214000.000000
max,2918.000000,190.000000,215245.000000,9.000000,2010.000000,2010.000000,1526.000000,6110.000000,755000.000000

In [6]:
#Check the missing value 

data.isnull().sum()

Id                 0
MSSubClass         0
MSZoning           4
LotArea            0
LotConfig          0
BldgType           0
OverallCond        0
YearBuilt          0
YearRemodAdd       0
Exterior1st        1
BsmtFinSF2         1
TotalBsmtSF        1
SalePrice       1459
dtype: int64

In [7]:
data.columns

Index(['Id', 'MSSubClass', 'MSZoning', 'LotArea', 'LotConfig', 'BldgType',
       'OverallCond', 'YearBuilt', 'YearRemodAdd', 'Exterior1st', 'BsmtFinSF2',
       'TotalBsmtSF', 'SalePrice'],
      dtype='object')

In [8]:
data = data.fillna(data.mean(numeric_only=True))

In [9]:
data = pd.get_dummies(data, drop_first=True)

In [10]:
# Define X and y
X = data.drop("SalePrice", axis=1)
y = data["SalePrice"]

In [11]:
# Train Test Split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [12]:
# Train Model
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [13]:
# Prediction
y_pred = model.predict(X_test)

In [14]:
y_pred

array([170295.07931642, 187320.31698233, 153913.49238616, 187163.00573202,
       202542.0667098 , 228149.34191604, 134826.65553818, 201780.80701599,
       129211.89929137, 183182.52684274, 166970.0885085 , 189994.02790453,
       182498.6830063 , 192407.17131466, 191638.24554605, 196067.1780279 ,
       162471.08154099, 206119.38942076, 146194.84751289, 170137.27547028,
       204160.77252499, 148230.17099051, 135372.6760254 , 205804.29174053,
       193831.51570488, 198766.3774763 , 190141.2462213 , 152586.63392895,
       186813.66666464, 168393.02907397, 217227.64084016, 156720.11640876,
       201300.63601651, 194769.00281254, 196693.23458008, 205844.19657692,
       163266.65291656, 167673.22938339, 158170.07019915, 163363.60759624,
       136241.90887256, 197375.86563108, 217752.07522078, 184844.72318087,
       175699.13477024, 189073.01438862, 190690.8566465 , 184611.13137829,
       195352.92467078, 223358.87763262, 152429.00489578, 163568.00101954,
       148468.03081432, 190670.9408947 , 164105.45104718, 133174.1777943 ,
       164307.86126632, 185793.37999856, 231103.99748992, 157490.38851944,
       154797.12120998, 135510.19062514, 176345.24043825, 151650.43910432,
       174847.78273781, 199134.80465445, 186198.44353197, 147412.11304912,
       167811.05886044, 158171.76624021, 201162.62029606, 160870.96608613,
       193963.20350632, 214621.8475927 , 114489.85977604, 119956.50341918,
       201987.72949872, 140562.34509407, 204352.12155392, 195812.78204276,
       169486.47240216, 192833.65187647, 175068.21822638, 161661.36458239,
       169933.96381144, 193970.02074817, 104871.94878804, 162454.98972138,
       143127.39534425, 176556.20209821, 172735.28122426, 146367.93624492,
       164395.58369368, 223696.32155849, 168478.10853781, 167610.00081806,
       187606.55306417, 196106.57100509, 143057.61475639, 182904.01685285,
       173453.51784449, 164739.45283058, 168478.53124065, 208872.29478149,
       184249.29012186, 168803.7442172 , 154101.25709919, 165573.47741602,
       220252.35851428, 176863.01550533, 164071.01237188, 152276.22224106,
       196034.57737561, 251522.86648114, 219625.42750663, 151900.82640933,
       154963.12516076, 191600.41414144, 244226.90905719, 204063.12374123,
       156188.43732606, 187046.83379122, 198586.07801353, 157560.70781309,
       156079.89432402, 169248.58929493, 148945.51105375, 198890.27281743,
       209203.53108761, 220625.92060648, 168068.08795884, 126832.30937538,
       180192.95573928, 178504.52534931, 154484.41696825, 175489.98374565,
       199184.8420683 , 194931.34044045, 237934.23331322, 210800.20247599,
       171976.87278467, 157837.42242395, 146260.69800586, 197960.58813883,
       217463.44309608, 215041.68407904, 191242.47756759, 234855.24815507,
       193387.39373953, 186512.57140417, 165548.6602199 , 217993.12005524,
       161063.71008347, 166747.87649907, 130876.15331435, 154685.79637615,
       198888.04626523, 205832.53415343, 156139.09088998, 113813.28607596,
       223933.88488239, 229973.3974809 , 206364.89659039, 169046.20150686,
       160432.23683876, 154069.86204239, 221674.58757021, 176252.27392916,
       172671.06597095, 172225.00479541, 160192.15507393, 161105.70177168,
       200417.97023447, 208114.66157303, 195674.16743737, 208412.94043661,
       150893.03533617, 192954.29196935, 161362.70971795, 209494.1554719 ,
       210494.92758224, 199745.7646202 , 158858.49796523, 204711.702589  ,
       198507.59505684, 215480.15770886, 194601.50731942, 239668.89513655,
       179907.56109955, 154766.8314104 , 215677.36552055, 207015.1372487 ,
       148565.18141142, 140855.57664473, 196787.62756852, 216041.82660633,
       210295.2576922 , 169381.97296531, 252244.09366216, 173778.87415073,
       169725.34242332, 180967.92582115, 176016.84284044, 160166.49780748,
       161949.75197032,  94053.34206314, 151590.52974228, 174566.85157726,
       155345.37771541, 191479.10103425, 147384.80005456, 181770.70727435,
       232648.08962549, 173958.81361063, 182766.6641624 , 138726.00772191,
       208946.50119298, 112108.95137203, 179213.4855279 , 192224.6024574 ,
       130725.35426126, 180993.83817424, 194014.80889086, 106844.06597364,
       234368.3762408 , 189680.50948475, 183192.48062856, 194190.16525054,
       147232.24352155, 117528.21378541, 155504.49461182, 176554.81378986,
       150006.32575592, 196279.04080562, 149714.39718353, 168218.05664913,
       160002.91118093, 193473.27199989, 140974.24238556, 129914.16546132,
       214214.34453396, 160460.67025432, 213941.23547952, 215347.08987   ,
       233335.92623921, 181350.26550407, 164294.67790426, 218419.89554892,
       182447.42996952, 168481.06396992, 198562.22571122, 174103.66449675,
       170825.26109766, 138190.52631543, 226288.01698679, 129579.93279296,
       134544.7129509 , 174798.20556497, 207585.07110936, 211119.67120293,
       162967.98455765, 180232.71880312, 158368.15045191, 212819.41589665,
       252435.57144623, 189299.41583443, 193652.8066069 , 190074.31171749,
       207029.92148506, 180366.61712662, 175758.17904275, 150880.99398283,
       167093.95372878, 144156.55916112, 207333.28575156, 202485.53631456,
       158906.44935781, 214016.41237963, 176776.27433597, 180244.49765248,
       218017.28036228, 182227.30039106, 163071.61974928, 145518.69255587,
       227331.55821895, 160029.49595829, 212283.88835817, 171137.099426  ,
       167111.99286202, 153915.80733264, 175513.2695649 , 197507.58080558,
       179699.28680025, 186465.81209672, 200036.60390578, 190757.68458688,
       234194.62449189, 153558.45858893, 167626.47252693, 169272.28421232,
       173198.47093729, 221580.26633857, 194257.22364423, 208302.76197799,
       150708.96223515, 242058.28261139, 195120.75748191, 229079.35966688,
       151475.8638477 , 194104.04678441, 193972.94131286, 180071.64017362,
       198944.00027921, 181419.01314913, 159566.14562211, 167114.11243735,
       137851.79915331, 153020.65960712, 216428.22036804, 165720.47567625,
       163737.60779681, 201717.9113778 , 217805.46795754, 106555.62883483,
       164751.61242505, 206942.11693249, 195072.24856607, 185514.00893048,
       100091.32459778, 175134.00573695, 150513.25198002, 191343.85799033,
       122127.63335721, 127418.84510175, 206662.1776075 , 146306.67522823,
       173057.85966837, 184396.84611676, 187508.56657147, 157276.25859122,
       149305.31865966, 183033.88400493, 167170.57894803, 176877.30665999,
       194204.06948225, 183527.56395584, 183065.78074727, 138798.8426594 ,
       164765.62965416, 120389.11651542, 168348.381534  , 188745.74631576,
       156878.40310308, 212372.78472311, 209338.82365535, 173771.98775002,
       142704.80852669, 195690.39101262, 151598.19235355, 219855.92591157,
       132957.52062888, 189942.41678729, 188429.05471033, 185806.58638431,
       184097.26990761, 192800.6206589 , 182822.16405898, 193418.78247794,
       189913.31200084, 180996.39598642, 166677.88093288, 157585.69029141,
       174534.18878958, 151778.68846597, 180742.27187172, 199107.13709745,
       168823.77989098, 174444.12346964, 197075.42502805, 157045.80599274,
       167185.39401026, 234245.18170473, 179157.49945327, 187559.52934015,
       148097.79932991, 207611.52888164, 191017.30672672, 151572.93757343,
       169686.89832587, 175479.87229061, 162328.5301591 , 221275.04388593,
       209330.80499693, 172520.08500283, 198589.70833456, 155537.75678116,
       202558.47218318, 212745.16656587, 162711.04863712, 179131.69687978,
       167512.84440305,  98326.34828737, 163885.671538  , 191074.45303636,
       158448.49529495, 210882.12772789, 138906.41134053, 198755.48526958,
       196671.23548231, 129202.85873191, 130658.78999015, 157543.85228036,
       169335.70027107, 199504.23405488, 149397.09994626, 195053.17816425,
       191845.54750601, 193957.84212945, 215854.8740886 , 229907.74271888,
       199505.13531556, 147150.98899785, 144924.86524354, 183244.44628795,
       188633.33632714, 210014.81221397, 223191.88971232, 248433.06963754,
       172303.91732551, 177291.49878122, 163456.74663874, 160934.37800229,
       177597.75995672, 199174.07373699, 179049.51237787, 158061.67216549,
       139483.72338131, 195818.52180588, 151437.61534335, 137514.08076283,
       180567.05228426, 148507.95639874, 173472.80269035, 232424.1359054 ,
       165559.72602866, 139505.98063835, 144613.98917033, 213895.12710275,
       189621.48049009, 145765.27509255, 212061.69594551, 160447.90750568,
       199301.66231999, 196081.9306775 , 165551.90385386, 154204.87230624,
       155555.18982134, 153381.56373452, 185143.37472136, 143349.28255602,
       173532.628943  , 199756.4286426 , 168581.4694538 , 246231.80022182,
       193332.48750624, 131652.5810257 , 162054.74218156, 269425.04422686,
       197795.97094044, 151943.14708162, 245647.87850219, 161706.71556946,
       214576.45286276, 201441.57728668, 207930.71922014, 202966.45445998,
       167234.8880301 , 226567.49473637, 191665.67278324, 134014.9941827 ,
       233322.52135368, 173498.2396913 , 143328.15805681, 214692.04496089,
       165707.7931578 , 160426.23935712, 166557.51563512, 170944.47939352,
       152607.5694236 , 194090.43717116, 208120.08253041, 178847.95267662,
       218672.678808  , 187068.43320053, 406190.13521349, 227997.27815317,
       184499.04450993, 206065.48306583, 147691.31110985, 166803.05398436,
       152264.87372216, 217965.49665563, 202681.88166682, 219498.06684639,
       131663.24859684, 185982.06925226, 143749.48108299, 206529.20909445,
       154950.12408687, 158905.06404285, 196170.78659901, 188955.74470167,
       171881.51916117, 182206.35223101, 217277.0195297 , 203220.65027944,
       165186.46356348, 210357.81791426, 162918.43948372, 199172.65096973,
       137369.59751938, 161660.86142789, 184300.10253084, 181124.08478396,
       169222.23147053, 150920.39259595, 232132.62283121, 196456.00808924,
       201844.61009479, 150979.32675546, 115080.98721912, 153674.62942916,
       260791.94756273, 194374.77688263, 188068.87656897, 157855.83902014,
       142296.2057919 , 161345.40999315, 210226.32260905, 190909.04872428,
       176751.42686499, 154845.22552358, 195843.48682774, 176370.06053102,
       154730.15662323, 146634.59975236, 171632.33702285, 145956.77928517,
       153220.26759085, 243251.89127522, 219243.09254047, 196649.80062657,
       177299.28976341, 181151.60858478, 230029.72529447, 132884.99656776,
       178850.2051862 , 197986.02118174, 135750.02967266, 165984.38832389,
       207683.50714878, 197796.56714275, 161385.8790893 , 158017.31681756,
       151006.49534614, 181069.5919378 , 139226.05636982, 151494.41443517,
       159193.44436229, 120383.85926165, 198486.33732628, 202956.31309275,
       149488.36473703, 171732.16206399, 173186.76061096, 155659.7566696 ,
       177611.43035467, 201941.14814088, 198805.79725198, 160850.97061548,
       236626.4900862 , 234048.59915042, 118111.4204888 , 196841.1010796 ])

In [15]:
# Evaluation
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)

print("MAE:", mae)
print("MSE:", mse)
print("RMSE:", rmse)
print("R2 Score:", r2)

MAE: 32608.615192308876
MSE: 2365951422.1109385
RMSE: 48641.04667984581
R2 Score: 0.3366572180561108